movies_back_office:
    resource: "@MoviesBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

movies_users:
    resource: "@MoviesUsersBundle/Controller/"
    type:     annotation
    prefix:   /user

movies_movies:
    resource: "@MoviesMoviesBundle/Resources/config/routing.yml"
    prefix:   /
