movies_users:
    resource: "@MoviesUsersBundle/Controller/"
    type:     annotation
    prefix:   /

movies_movies:
    resource: "@MoviesMoviesBundle/Resources/config/routing.yml"
    prefix:   /movies
