movies_series:
    resource: "@MoviesSeriesBundle/Resources/config/routing.yml"
    prefix:   /

movies_back_office:
    resource: "@MoviesBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

movies_movies:
    resource:    "@MoviesMoviesBundle/Resources/config/routing.yml"
    prefix:    /
    
login:
    pattern:    /login
    defaults:   { _controller: MoviesUserBundle:Security:login }

signin:
    pattern:    /signup
    defaults:   { _controller: MoviesUserBundle:Security:signup }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout