movies_actor:
    resource: "@MoviesActorBundle/Resources/config/routing.yml"
    prefix:   /

movies_home:
    resource: "@MoviesHomeBundle/Resources/config/routing.yml"
    prefix:   /

movies_back_office:
    resource: "@MoviesBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

movies_movies:
    resource:    "@MoviesMoviesBundle/Resources/config/routing.yml"
    prefix:    /
    
login:
    pattern:    /login
    defaults:   { _controller: MoviesUserBundle:Security:login }

signup:
    pattern:    /signup
    defaults:   { _controller: MoviesUserBundle:Security:signup }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

profil:
    pattern: /profil/{id}
    defaults: { _controller: MoviesUserBundle:Security:showProfil }
    requirements:
        id: \d
