movies_back_office:
    resource: "@MoviesBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /admin

movies_users:
    resource: "@MoviesUsersBundle/Controller/"
    type:     annotation
    prefix:   /users

movies_movies:
    resource: "@MoviesMoviesBundle/Resources/config/routing.yml"
    prefix:   /
