<?php

namespace Movies\MoviesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesRepository extends EntityRepository
{
    public function findByLetter($letter)
    {
       $qb = $this->createQueryBuilder('m');
       $qb->where('m.titre like :titre')->setParameter('titre',$letter.'%');

       return $qb->getQuery()->getResult();
    }
}

