movies_moviesbundle_movies:
    path:   /movies/{lettre}
    defaults: { _controller: MoviesMoviesBundle:Movies:movies }
    requirements:
        lettre: ^[A-Z]

movies_moviesbundle_moviesAll:
    path: /movies
    defaults: { _controller: MoviesMoviesBundle:Movies:moviesAll }

movies_moviesbundle_listGenre:
    path: /list-genre
    defaults: { _controller: MoviesMoviesBundle:Movies:listGenre }

movies_moviesbundle_showMovie:
    path: /show-movie/{id}
    defaults: { _controller: MoviesMoviesBundle:Movies:showMovie }
    requirements:
        id: \d.*
