parameters:
#    movies_movies.example.class: Movies\MoviesBundle\Example

services:
#    movies_movies.example:
#        class: %movies_movies.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
