movies_series_homepage:
    path:     /series
    defaults: { _controller: MoviesSeriesBundle:Series:index }

movies_series_showSerie:
    path: /show-serie/{id}
    defaults: { _controller: MoviesSeriesBundle:showSerie }
    requirements:
        id: \d

