movies_back_office_homepage:
    path:     /admin
    defaults: { _controller: MoviesBackOfficeBundle:Admin:index }

movies_back_office_manageMovies:
    path:   /ajouter-un-film
    defaults: { _controller: MoviesBackOfficeBundle:Admin:manageMovie }
    
movies_back_office_manageActeur:
    path: /ajouter-un-acteur
    defaults: { _controller: MoviesBackOfficeBundle:Admin:manageActeur }

movies_back_office_manageRealisateur:
    path: /ajouter-un-realisateur
    defaults: { _controller: MoviesBackOfficeBundle:Admin:manageRealisateur }