movies_back_office_homepage:
    path:     /admin
    defaults: { _controller: MoviesBackOfficeBundle:Admin:index }

movies_back_office_addMovies:
    path:   /admin/ajouter-un-film
    defaults: { _controller: MoviesBackOfficeBundle:Admin:addMovie }
    
movies_back_office_addActeur:
    path: /admin/ajouter-un-acteur
    defaults: { _controller: MoviesBackOfficeBundle:Admin:addActeur }

movies_back_office_addRealisateur:
    path: /admin/ajouter-un-realisateur
    defaults: { _controller: MoviesBackOfficeBundle:Admin:addRealisateur }

movies_back_office_addGenre:
    path: /admin/ajouter-un-genre
    defaults: { _controller: MoviesBackOfficeBundle:Admin:addGenre }

movies_back_office_addRole:
    path: /admin/ajouter-un-role
    defaults: { _controller: MoviesBackOfficeBundle:Admin:addRole }

movies_back_office_modifyMovie:
    path:   /admin/modifier-un-film/{id}
    defaults: { _controller: MoviesBackOfficeBundle:Admin:addMovie }
    requirements:
        id: \d.*
 
movies_back_office_listMovies:
    path: /admin/liste-des-films
    defaults: { _controller: MoviesBackOfficeBundle:Admin:listMovies }

movies_back_office_deleteMovie:
    path: /admin/supprimer-un-film/{id}
    defaults: { _controller: MoviesBackOfficeBundle:Admin:deleteMovie }
    requirements:
        id: \d.*
