Movies\ActorBundle\Entity\Actor:
    type: entity
    table: null
    repositoryClass: Movies\ActorBundle\Entity\ActorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        image:
            type: text
        nomComplet:
            type: string
            length: 255
        biographie:
            type: text
    lifecycleCallbacks: {  }
