Movies\ActorBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: Movies\ActorBundle\Entity\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        role:
            type: string
            length: 255
    lifecycleCallbacks: {  }
