<?php

namespace Movies\ActorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActorRoleMovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRoleMovieRepository extends EntityRepository
{
}
